### ISSUE TITLE
Source for colors.py script in the first example image?

### ISSUE THREAD

**Issue by jason5122** [robinbentley/oceanic-next-macos-terminal#1]
Hi, this isn't an issue or bug report, but could you please share the script for `colors.py` in the first example in the README? It seems pretty useful to test my terminal colors..

This is the image I'm referring to:
<img width="842" alt="ss-colors" src="https://user-images.githubusercontent.com/34594853/101134597-a3aa7f00-35d8-11eb-943b-b6b7ebf73cae.png">

**Comment by jason5122** [comment]
Also, would you mind sharing your configuration for your prompt (i.e., PS1 stuff)? I like the different color for the username, cwd, Git branch status, etc.

**Comment by robinbentley** [comment]
Hi @jasonhan-vassar, of course. Everything you need is in my dotfiles repo. It's basic and a little old now but it does what I like so have had no reason to update it. If you look in `prompt.sh` you can see what's going on.

https://github.com/robinbentley/dotfiles/tree/master/shell 

Let me know if you need anything else, if not then please close the issue when you're sorted 👍 

EDIT: Sorry didn't answer your original question the color test is here, I've swapped the python one for a shell script since then
https://github.com/robinbentley/dotfiles/blob/master/resources/colortest.sh

This is the output
<img width="637" alt="Screenshot 2020-12-04 at 15 06 38" src="https://user-images.githubusercontent.com/2156395/101179615-624eb980-3642-11eb-9343-306e3854c6cf.png">

**Comment by jason5122** [comment]
Thanks a lot 😁
